### ISSUE TITLE
NewsDataSource - Unexpected nil User

### ISSUE THREAD

**Issue by ajfigueroa** [twostraws/Unwrap#1]
First off, I want to say that the app looks awesome! 😃 
I ran into a compilation issue on the way to work that I thought I would file here.
I might just be missing something so I apologize in advance if that's the case.

# Hardware
- Xcode 9.3
- iPhone X Simulator (11.4)

# Error
I see the following error:
```
Fatal error: Unexpectedly found nil while unwrapping an Optional value
```

for this [line](https://github.com/twostraws/Unwrap/blob/master/Unwrap/Activities/News/NewsDataSource.swift#L24)

```swift
// NewsDataSource.swift
var containsNewArticles: Bool {
    get {
        if let newestArticleID = articles.first?.id {
            // This line here
            if newestArticleID > User.current.latestNewsArticle {
                return true
            }
        }
     set {
    ....
}
```

# Possible Solution

A quick fix I added to get the app to compile is to conditionally unwrap the `User.current` as so:
```swift
if let user = User.current, newestArticleID > user.latestNewsArticle {
```

However, I think it would help to understand why `User.current` was nil in the first place to see if this is the best fix. There are other places where `User.current` is being used so it could possibly affect other areas.

**Comment by vince105** [comment]
I was able to run this without a problem on my device (iPhone 7+, iOS 12 beta 6) but it would crash in the simulators due to this issue.

**Comment by twostraws** [comment]
Up to just a few days ago, I had this in User-StaticProperties.swift: `static var current = User()` – that creates an empty user regardless, which meant the AppDelegate could just check the result from load() and only change `User.current` if it got a non-nil return. However, that wouldn't fix the fact that this feels like a race condition. 

Does this happen consistently without your change? If so, can you check whether the user code in AppDelegate.swift is actually being hit before the news data source is being created?

**Comment by fivenorth** [comment]
It appears this is *not* the case when running in the simulator: https://cl.ly/0o3X2W3A2G3d.

**Comment by fivenorth** [comment]
No worries! All good. And it looks to be a wonderful resource. Thanks for all the effort! :)

**Comment by twostraws** [comment]
Please pull that change – I believe it should solve the issue.
