### ISSUE TITLE
Crash in taptocode/rearrange exercise

### ISSUE THREAD

**Issue by elitree** [twostraws/Unwrap#101]
device: iPhone 6s, iOS 12.1.4

I'm not sure exactly how to reproduce, and unfortunately I've only seen it once, but I crashed today in one of the exercises during my first daily quiz. Unfortunately I didn't think at the time to grab a screenshot or call stack.

The problem itself asked the user to drag the tiles into the working area to complete an expression using the ternary operator to return a true value for a new constant if both existing variables were true (or something like that).  The app froze when I dragged the equals sign into the working area (I think I had most of the other tiles in place already). 

At first I didn't realize it had crashed, but when I returned to Xcode I saw it stopped on Unwrap/Activities/Practice/TapToCode/TapToCodeModel.swift line 67, "usedWords.insert(word, at: destinationIndexPath.item)".  There was an out of bounds exception, I believe.

Sorry for the lack of information here. If I knew an easy way to return to this problem I'd give it a shot and see if I could reproduce. If you have any suggestions or want me to try anything, I'm happy to do so.

Thanks for writing this fantastic app!

-Eli

**Comment by twostraws** [comment]
I believe this is resolved now – thank you!
