### ISSUE TITLE
Bitrise Setup

### ISSUE THREAD

**Issue by mleatherb** [twostraws/Unwrap#102]
Since this is an open source project there should be CI setup on the repo. Paul would need to setup the tokens. I'd be happy to setup the build configs for the project. 

Bitrise also offers free upgraded plans for open source projects. More info can be found here. 
https://blog.bitrise.io/free-developer-plan-features-for-open-source-projects-on-bitrise

**Comment by twostraws** [comment]
This has now been done – thanks for the feedback!
