### ISSUE TITLE
New TestFlight build 6 did not persist UserDefaults from earlier build

### ISSUE THREAD

**Issue by wayni208** [twostraws/Unwrap#112]
![GitHawk Upload by wayni208](https://i.imgur.com/mqkbcqn.jpg)

Please close if this is a non issue. 

This was was a reply to your tweet regarding the new TestFlight build released yesterday. As far as I can tell, this could but should not happen. I have not seen this type of issue outside of TestFlight. 

I noticed that, in TestFlight, earlier builds are not being listed when I go to TestFlight>Unwrap - Learn Swift>Previous Builds>1.0

If you would like, I could test this via a closed TestFlight and see if this will continue to be a problem.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by twostraws** [comment]
I don't know how TestFlight persists data across betas – maybe it zaps the data every time? Certainly we aren't do anything special.

**Comment by wayni208** [comment]
I found only one StackOverflow answer which said that the data is zapped between builds for security purposes. [https://stackoverflow.com/q/35196228/11125483](url). I don’t believe he is correct.

Looking through Apple’s “App Testing Guide” [https://developer.apple.com/library/archive/technotes/tn2431/_index.html#//apple_ref/doc/uid/DTS40017497-CH1-APP_TESTING_PROCEDURE-4__TEST_AN_APP_UPDATE](url) leads me to believe that these persist between updates as long as the bundle ID doesn’t change. This article seems kind of old (2016) but between this and the multitude of StackOverflow answers saying this data should persist leads me to believe it should persist. 

The “App Testing Guide” provides guidance on how to test updates. I can, and will, do this testing. I have a new 12.9 iPad upgrade showing up today 🎉(Apple, you can release Xcode on iPad now, please) so can test on a new device. And you mentioned that you might release one more TestFlight build so that should be a definitive test if it occurs. 

Why his install failed? He could have deleted and then installed? Doubtful. Could it be because the initial user load is done asynchronously? I can _possibly_ see that with an iCloud sync as it is left to the system to make that occur. But his UserDefaults, all things being equal, should already exist and load, regardless. 

I’m unfamiliar with TestFlight. Does it give you analytics as far as adoption rates of the new build from the old one? I would expect if this were a big issue that more than one person would be reporting this.

**Comment by wayni208** [comment]
No issues installing on a new device or updating old device. Everything persists as expected. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
