### ISSUE TITLE
Daily challenge progress

### ISSUE THREAD

**Issue by NickSet** [twostraws/Unwrap#122]
I'm not sure if this is intended behavior, but you can answer a couple of questions on the daily challenge and then close the app. Opening the app back up has the daily challenge reset as if you haven't attempted it.

I believe it should track a user's progress so that the daily challenge can be completed throughout the day and not all at once.

**Comment by twostraws** [comment]
I am aware of it, and I'm not terribly concerned – if folks want to "cheat" by doing that, the only person they are cheating is themselves.

**Comment by NickSet** [comment]
Okay, I just wanted to bring it to your attention. I was thinking of it more from a UX perspective than from users cheating themselves. It doesn't take terribly long to finish the challenge, but it could be nice if users have the option to do a question here or there when time permits and the app tracking their progress.

Side note: I think the app is awesome. I'm a big fan of the clean UI as well.
