### ISSUE TITLE
Correct result not honoured

### ISSUE THREAD

**Issue by TyrfingMjolnir** [twostraws/Unwrap#125]
![IMG_0031](https://user-images.githubusercontent.com/4602183/57550756-89121480-7367-11e9-8067-0103176fbab9.jpeg)

As pr Playground below

```
import Cocoa

print ( [1,5,2,5,3,5].filter{ $0 % 5 == 0 }.compactMap{ $0 / 5 } .reduce( 0, + ) )
```
```
3
```

**Comment by twostraws** [comment]
Definitely won’t fix.
