### ISSUE TITLE
No such module 'SwiftEntryKit'

### ISSUE THREAD

**Issue by flyingalex** [twostraws/Unwrap#13]
![image](https://user-images.githubusercontent.com/11313145/43997643-edd8881a-9e13-11e8-8158-569ef4d17298.png)

I saw this error when i build, seems can't find all the dependencies
can you take a look? thx

xcode: Version 9.4.1
swift: 4.1

**Comment by twostraws** [comment]
Please make sure you open the workspace, not the project.

**Comment by flyingalex** [comment]
works, thx very much
