### ISSUE TITLE
iOS Glyph icons for Tab Bar navigation

### ISSUE THREAD

**Issue by m5o** [twostraws/Unwrap#131]
Hey 👋

Thank you for sharing your knowledge by creating this app & repo. 🤘
I'm discovering Swift lately and really like your resources. 
Coming from a design background wanted to share the free iOS glyphs icon library from @icons8 
Their complete library is huge and the iOS style. The [license](https://icons8.com/license) would be fit for this project.

📱https://icons8.com/ios 
👩‍⚖️https://icons8.com/license

You're using Font Awesome and this resource is great and often used in web development. Maybe the iOS glyph icons would make the tab bar more Apple like. 

What do you think? Is it worth, otherwise just see it as a link reference. ✌️

**Comment by twostraws** [comment]
Hello! Thank you for your feedback; I'm quite happy with the current icons.
