### ISSUE TITLE
No such module 'SwiftEntryKit'

### ISSUE THREAD

**Issue by gitcri** [twostraws/Unwrap#14]
I downloaded the Zip, extracted it, opened the Xcode project file and tried to compile it without any changes. But the project doesn't compile. Instead it shows this error:
```
Swift Compiler Error
No such module 'SwiftEntryKit'
ChallengesCoordinator.swift 
```

**Comment by rizwankce** [comment]
Duplicate of #13 
Please make sure you open the workspace, not the project file. @gitcri

**Comment by gitcri** [comment]
Yes, my mistake. Sorry. Thank you!
