### ISSUE TITLE
Localization

### ISSUE THREAD

**Issue by BasThomas** [twostraws/Unwrap#141]
I saw [some user-facing strings](https://github.com/twostraws/Unwrap/blob/e8d2da394ac3326c3ef8255a09eb0118cc1e147d/Unwrap/Activities/Home/HomeDataSource.swift#L195) that are not wrapped in an `NSLocalizedString` and I was wondering about the plans of localizing the app?

It might be a good idea to prepare for that, and it could be a nice task to get an overview of the code base. :)

(I might want to pick this one up myself 😄)

**Comment by twostraws** [comment]
Yes, I'm afraid the app isn't set up for localization right now – it might be a rather tricky prospect given the very large amount of data it contains. That being said, if you'd like to localize strings in the Swift code, go for it!

**Comment by BasThomas** [comment]
This is coming along quite nicely :)

**Comment by twostraws** [comment]
Can I assume, given your job situation @BasThomas, that this can be closed? 😅

**Comment by BasThomas** [comment]
Someone else could pick it up! But feel free to close; I'm not currently working on it.
