### ISSUE TITLE
command phasescriptexecution failed with a nonzero exit code xcode 11.3.1

### ISSUE THREAD

**Issue by Shivani-Bajaj** [twostraws/Unwrap#157]
**Steps to reproduce:**
1. Clone the project and run in Xcode 11.3.1
2. Build the project and the build fails stating the error "command phasescriptexecution failed with a nonzero exit code"

**Comment by rahulrs0029** [comment]
This looks like issue in Xcode. Try cleaning and building again.

**Comment by Shivani-Bajaj** [comment]
@rahulrs0029 tried the same but the issue wasn’t in the Xcode, it was in swiftlint run script. I have resolved it and it’s merged now :)
