### ISSUE TITLE
Unwrap requires return keyword

### ISSUE THREAD

**Issue by johnrnyquist** [twostraws/Unwrap#165]
The Swift language allows single line functions to omit the return keyword. Unwrap currently sees omitting the return keyword as an error, for example:

func a(_ n: Int) -> Int { n * n }

Would be considered incorrect.

**Comment by l-rettberg** [comment]
Same issue with the following Free Coding Problem: "Write a function that accepts two Doubles and returns their product. For example, sending in 3, 5 will return 15."

The function below is valid Swift - but is viewed as an error by Unwrap
func m(_ d1: Double, _ d2: Double) -> Double { d1 * d2 }

**Comment by Carrione** [comment]
Solved - see PR #174 and #177
