### ISSUE TITLE
No such module 'SwiftEntryKit'

### ISSUE THREAD

**Issue by emilshouse** [twostraws/Unwrap#17]
I just downloaded the app and attempted to run it and got the below error. I'm not too familiar with cocoapods so not sure what's missing. 
<img width="630" alt="screen shot 2018-08-14 at 9 36 33 pm" src="https://user-images.githubusercontent.com/22759260/44131810-43e75586-a00a-11e8-917d-46124e4610ba.png">

**Comment by twostraws** [comment]
Please open the workspace, not the project.

**Comment by emilshouse** [comment]
Thanks! That resolved it.
