### ISSUE TITLE
Typo: "if someone sat an exam"

### ISSUE THREAD

**Issue by duianto** [twostraws/Unwrap#203]
Typo: "if someone sat an exam"
>For example, if someone sat an exam we could print different messages depending on their score:

source:
https://github.com/twostraws/Unwrap/blob/52d0a7a9c19c6bb78b7ea8c168a18838bc4ccefd/Unwrap/Content/SixtySeconds/range-operators.html#L3

### Expected
"if someone's at an exam"

>For example, if someone's at an exam we could print different messages depending on their score:

**Comment by twostraws** [comment]
The text is correct: "to sit an exam" means to sit in the exam room and complete the exam paper.

**Comment by duianto** [comment]
Thanks for the correction.

If someone else wonders the same thing, then this might also be helpful.
>British people sit an exam, Canadians write an exam, Americans take an exam.

source: https://www.quora.com/In-English-grammar-does-a-person-sit-an-exam-or-sit-for-an-exam
