### ISSUE TITLE
Typo: "prints", Expected: "print"

### ISSUE THREAD

**Issue by duianto** [twostraws/Unwrap#209]
Typo: "prints"
Expected: "print"
https://github.com/twostraws/Unwrap/blob/3a5ee7f0ec6315791f3f9175438c385a623ba2b4/Unwrap/Content/SixtySeconds/copying-objects.html#L12

Before: `<p>If we create an instance of that class and prints its name, we’ll get “Taylor Swift”:</p>`
After: `<p>If we create an instance of that class and print its name, we’ll get “Taylor Swift”:</p> `

**Comment by twostraws** [comment]
This is corrected now – thank you!
