### ISSUE TITLE
FreeCoding: All items capitalized. A working solution is not accepted.

### ISSUE THREAD

**Issue by duianto** [twostraws/Unwrap#214]
FreeCoding: All items capitalized. A working solution not accepted.

In the FreeCoding exercise:
>Write code that creates an array of all the items in <code>words</code>, capitalized. So, your finished array should contain THE, RAIN, IN, SPAIN."

https://github.com/twostraws/Unwrap/blob/7344eeb6bef109d2710dd12dcadefc8f4fd9b236/Unwrap/Activities/Practice/FreeCoding/FreeCoding.json#L222

The following working solution isn't accepted:
```swift
let words = ["The", "rain", "in", "Spain"]
var uppercased: [String] = []
for word in words {
  uppercased.append(word.uppercased())
}
```

It does work on replit:
https://replit.com/languages/swift

Printing the capitalized array:
```swift
print(uppercased)
```
Outputs:
```swift
["THE", "RAIN", "IN", "SPAIN"]
```

### A possible cause:
The accepted answers:
https://github.com/twostraws/Unwrap/blob/7344eeb6bef109d2710dd12dcadefc8f4fd9b236/Unwrap/Activities/Practice/FreeCoding/FreeCoding.json#L226

Only accepts empty arrays that are initialized like this:
```swift
var uppercased1:[String] = [String]()
```

The lesson: `Creating empty collections`, demonstrates this method:
https://github.com/twostraws/Unwrap/blob/3a5ee7f0ec6315791f3f9175438c385a623ba2b4/Unwrap/Content/SixtySeconds/creating-empty-collections.html#L21
```swift
var results = [Int]()
```

### However
Another FreeCoding question does accept:
```swift
var newArray:[Int] = []
```
https://github.com/twostraws/Unwrap/blob/7344eeb6bef109d2710dd12dcadefc8f4fd9b236/Unwrap/Activities/Practice/FreeCoding/FreeCoding.json#L144

According to the answers in this thread:
https://stackoverflow.com/questions/30430550/how-to-create-an-empty-array-in-swift

There are multiple ways of creating an empty array.

https://stackoverflow.com/a/42464309
This commenter said: "shorthand syntax way is always preferred."

Method 1: Shorthand Syntax
```swift
var arr = [Int]()
```

Method 2: Array Initializer
```swift
var arr = Array<Int>()
```

Method 3: Array with an Array Literal
```swift
var arr:[Int] = []
```

Method 4: Credit goes to @BallpointBen
```swift
var arr:Array<Int> = []
```

And a later comment suggests two other methods (the first and last):
https://stackoverflow.com/a/51258735
```swift
var myArray: Array<String> = Array()
var myArray = [String]()
var myArray: [String] = []
var myArray = Array<String>()
var myArray:Array<String> = []
```

But the last comment:
https://stackoverflow.com/a/56917862
links to the Apple developer page (Array).

Where the Overview section
https://developer.apple.com/documentation/swift/array#overview
says:
>You can create an empty array by specifying the Element type of your array in the declaration. For example:
```swift
// Shortened forms are preferred
var emptyDoubles: [Double] = []

// The full type name is also allowed
var emptyFloats: Array<Float> = Array()
```

### Summary
It might be overkill to support all methods mentioned above.

But since apple suggests:
```swift
var emptyDoubles: [Double] = []
```
And `Unwrap: Swift` already accepts it in one of the FreeCoding questions,
then it might be good to also accept this method in the question:
>Write code that creates an array of all the items in <code>words</code>, capitalized. So, your finished array should contain THE, RAIN, IN, SPAIN."

https://github.com/twostraws/Unwrap/blob/7344eeb6bef109d2710dd12dcadefc8f4fd9b236/Unwrap/Activities/Practice/FreeCoding/FreeCoding.json#L222

### Environment
* Unwrap app version: 1.5
* iOS version: 14.7.1 (18G82)
* Device: iPhone X

**Comment by Carrione** [comment]
The issue can be closed.
