### ISSUE TITLE
Apple iOS keyboard closed range issue

### ISSUE THREAD

**Issue by duianto** [twostraws/Unwrap#215]
Three periods on the Apple iOS keyboard, are replaced with a single three dot character. This character is not accepted as a range. 

Workaround:
The period key on the right side of the first symbols row, above the Apple iOS keyboard, keeps the periods as separate characters when three periods are typed.

Screen recording:
The recording starts on the Free Coding exercise:
"Write code that loops from 1 through 100 to create an array of all even numbers."

A working solution has been typed in, without the range. 

The cursor is between "in" and "{" in the for loop. 

A 1 is typed. 

Three periods: .
are typed at the bottom left of the Apple iOS keyboard. 

When the third period is typed, then the three periods are replaced with a single character that shows three dots that are close together.

100 is typed. 

The top right button: Done
Is tapped.
The keyboard is hidden. 

The bottom button: Submit
Is tapped. 
A pop up appears:
"That's not quite right!"

OK is tapped on the pop up, and it closes. 

The code is tapped, between the three dot character and 100. 
The keyboard opens. 

The bottom right erase key is tapped. 
The three dot character is erased. 

Three periods are typed, with the top right period key, on the first row of symbols, above the Apple iOS keyboard. 
The three periods remain as three separate characters. 

The top right button: Done
Is tapped.
The keyboard is hidden. 

The bottom button: Submit
Is tapped.
The button turns green, and a checkmark appeared to the left of the button text.

https://user-images.githubusercontent.com/13420573/132851387-f07e4dcc-9994-44cd-bf36-90687b0ef469.MOV

### Environment
* Unwrap app version: 1.5
* iOS version: 14.7.1
* Device: iPhone X

**Comment by robinlmp** [comment]
Thanks, I’d started working on this before the problem was posted so missed it. Hopefully this is resolved with my PR.

**Comment by Carrione** [comment]
This issue can be closed.
