### ISSUE TITLE
FreeCoding hint says: `isMultiple(of:)`, but it's not listed in the answers

### ISSUE THREAD

**Issue by duianto** [twostraws/Unwrap#216]
In the FreeCoding exercise:
>"Write code that loops from 1 through 100 to create an array of all even numbers."

https://github.com/twostraws/Unwrap/blob/7344eeb6bef109d2710dd12dcadefc8f4fd9b236/Unwrap/Activities/Practice/FreeCoding/FreeCoding.json#L243

The hint says that one can use: `isMultiple(of:)`
>"You'll need to use the division remainder operator, <code>%</code>, or the isMultiple(of:) method."

but `isMultiple` is not listed in the answers:
https://github.com/twostraws/Unwrap/blob/7344eeb6bef109d2710dd12dcadefc8f4fd9b236/Unwrap/Activities/Practice/FreeCoding/FreeCoding.json#L247

### Note
This seems like it could be a problem, but I haven't tested if `isMultiple` is accepted.

Because the question had already been answered correctly using `%` while making a screen recording for another issue.
FreeCoding: All items capitalized. A working solution is not accepted. #214

Environment
* Unwrap app version: 1.5
* iOS version: 14.7.1 (18G82)
* Device: iPhone X

**Comment by Carrione** [comment]
The issue can be closed.
