### ISSUE TITLE
Valid solution for a puzzle not accepted

### ISSUE THREAD

**Issue by fmad** [twostraws/Unwrap#248]
In the daily challenge where you are asked to free-style uppercasing an array of words, it does not accept my solution even though it works in the playground.

### Steps to reproduce

For this problem:
let words = ["The", "rain", "in", "Spain"]

this solution works but is not accepted:
let caps = words.description.uppercased()

### Expected behavior

Mark as correct

### Actual behavior

Considers the puzzle failed

### Environment

* iOS Version: 17.1.2
* Unwrap App Version: No idea - downloaded from AppStore 2 days ago
* Device: iPhone 13 Pro

**Comment by twostraws** [comment]
This is not a valid solution and will not be accepted.

**Comment by fmad** [comment]
Sorry, missed your comment as I've been busy moving house. I guess it all depends on what your definition of "valid" is - for me, it is: "the above code gives the results expected", and if you dare try it in swift you'll see it does indeed work.
But I am fine with the narrower range of accepted solutions, I've since realized how this program works, so no biggie.

**Comment by twostraws** [comment]
This isn't about me "daring" to try it – I can see exactly what the code does, and I can promise you it's invalid. By calling "description" on the array you're converting the whole thing to a string: it is no longer an array, no matter how it is formatted in a playground. The challenge specifically says you must "write code that creates an array of all the items", not a string. If you'd like to see the problem in more detail, try looping over your `caps` value and see what you get for each element.
