### ISSUE TITLE
Valid solution not accepted for counting 5s in an array

### ISSUE THREAD

**Issue by fmad** [twostraws/Unwrap#250]
The exercise that goes:
"Write code that goes over this array, counting the number of times it contains the number 5, then printing that total", does not accept a simple valid solution:

### Steps to reproduce

This code works but is not accepted:

```
let numbers = [1, 5, 2, 5, 3, 5]
var count=0
for i in numbers {
  if i == 5 {
    count += 1
  }
}
print(count)

```
### Expected behavior

It should count as correct, not failed

### Actual behavior

![image](https://github.com/twostraws/Unwrap/assets/1113955/b0725302-d38b-4260-a1fe-3096078f6cfa)

### Environment

* iOS Version: 17.2.1
* Unwrap App Version: 
* Device: iPhone 13 Pro

**Comment by Harry-KNIGHT** [comment]
Did you have another working solution for compare ?

**Comment by Harry-KNIGHT** [comment]
It's totally normal this solution doesn't work

Swift does not accept `var count=0`, it will ask you to have this syntax `var count = 0`

For me your answer is not good.

**Comment by fmad** [comment]
Sorry, missed the comment as I've been busy moving houses.

![image](https://github.com/twostraws/Unwrap/assets/1113955/a39e1071-e510-4957-8a18-f88de07ac1c6)

Swift playgrounds seems to like it enough as you can see from above snapshot.

I'm not too fussed though, I realized by now that this program has a set fixed number of "good" answers and I'm done with the challenges anyway, so there's no point in keeping this open.
