### ISSUE TITLE
Progress on challenges?

### ISSUE THREAD

**Issue by mike011** [twostraws/Unwrap#30]
It would be awesome too see how far along on the challenges you are!

**Comment by wayni208** [comment]
![Simulator Screen Shot - iPhone Xʀ - 2019-04-25 at 21 54 50](https://user-images.githubusercontent.com/47953083/56782780-e02fbb00-67a5-11e9-his9767-338331b4b12f.png)

Is this similar to what you are after, @twostraws?

**Comment by wayni208** [comment]
![GitHawk Upload by wayni208](https://i.imgur.com/wZijgI9.jpg)

Something like this?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by twostraws** [comment]
I think the hope was to see how you are doing with the badges below that, which is a much bigger job. For example, the "It's Complicated" badge requires you to read all the Complex Types chapters, but if you've only read 5 of them it should say something like "Progress: 5/11" in the alert that's shown when you tap the badge.

**Comment by wayni208** [comment]
I understand better now. Ok. Back to it. 🙂

**Comment by twostraws** [comment]
I believe this is resolved now. Thank you!
