### ISSUE TITLE
Highlight issues

### ISSUE THREAD

**Issue by mike011** [twostraws/Unwrap#32]
![image](https://user-images.githubusercontent.com/705433/44958543-a8d76b80-aeaf-11e8-9383-087903732870.png)

- The 0 from 32.0 is the wrong colour 
- The .5 from 12.5 is the wrong colour
- The _000 from 100 is also in the wrong colour. Might be a different issue.

**Comment by twostraws** [comment]
I believe this is now resolved – thank you for your help!
