### ISSUE TITLE
Add to TestFlight (Recommendation / Request)

### ISSUE THREAD

**Issue by vcapilladeveloper** [twostraws/Unwrap#38]
Hi, 

This is a very good tool for lear but I think would be useful for all users that you publish a Testflight Link for recive the last updates in our devices directly.

**Comment by rahulrs0029** [comment]
@twostraws has published TestFlight link on their Twitter account.
[Link to the Tweet](https://twitter.com/twostraws/status/1057753183286636544)
[TestFlight Link]( https://testflight.apple.com/join/ROxI9xSR)
