### ISSUE TITLE
Daily Challenge 8/9 error

### ISSUE THREAD

**Issue by swiftyjeffrey** [twostraws/Unwrap#4]
I can't remember the exact code but it's something like below. "Odd number" was the correct answer, but "Even number" was the accepted answer.

```swift
        let multiplied = 81
        if multiplied % 2 == 0 {
            print("Even number")
        } else {
            print("Odd number")
        }
```

**Comment by swiftyjeffrey** [comment]
Interesting. I thrice checked the input. 🤔

**Comment by twostraws** [comment]
It was definitely a mistake – please try again with the latest version!
