### ISSUE TITLE
Problem in a Daily Challenge question

### ISSUE THREAD

**Issue by rahulrs0029** [twostraws/Unwrap#50]
Today I got this **Predict the Output** challenge.

In the code shown in the challenge, there are no variable named `age2` and `age3`. Instead there are `numberOfUsers2` and `bottles3`.

<img src="https://user-images.githubusercontent.com/21116964/47844989-c78fab00-dde9-11e8-9def-0626b38628bc.png" width="250">

**Comment by mike011** [comment]
Addressed by: https://github.com/twostraws/Unwrap/pull/57
