### ISSUE TITLE
not compiling on xcode 10

### ISSUE THREAD

**Issue by espeneric** [twostraws/Unwrap#54]
lots of deprecations coming from pods, etc.

**Comment by rahulrs0029** [comment]
I’m using Xcode 10.1 and it works fine on my machine.

**Comment by espeneric** [comment]
maybe you converted the project with xcode 9 previously, try re-downloading, installing pods again.

**Comment by twostraws** [comment]
Another possibility is that you tried to update the pods, which isn’t needed – they all come included.

**Comment by espeneric** [comment]
you were right
