### ISSUE TITLE
Can't build. Getting errors in SwiftEntryKit

### ISSUE THREAD

**Issue by mike011** [twostraws/Unwrap#56]
- Deleted derived data
- Ran pod install
- Made sure I have the latest master version 
- Using Xcode 10

Steps:
- Try to build Unwrap in the workspace.

<img width="751" alt="screen shot 2018-11-13 at 7 37 48 am" src="https://user-images.githubusercontent.com/705433/48413926-38eb2a00-e717-11e8-97aa-f0e5c2be8fde.png">

**Comment by twostraws** [comment]
Try cloning but not touching the pods.

**Comment by Ninjoe-142** [comment]
Having the same problem. It doesn't build before touching the pod file and after instaling the pod file using CocoaPods.app the app still won't build. I checked Github desktop and these files have changed according. It looks to me that you are using CocoaPods 1.5.3 and we are using 1.5.2 but according to [the website](https://cocoapods.org/app) 1.5.2 is the most recent version.

<img width="961" alt="screen shot 2018-11-13 at 4 36 16 pm" src="https://user-images.githubusercontent.com/18401530/48444586-5a253800-e762-11e8-9a7b-8ada2e46faff.png">
<img width="698" alt="screen shot 2018-11-13 at 4 36 33 pm" src="https://user-images.githubusercontent.com/18401530/48444591-5db8bf00-e762-11e8-843d-d555fd4da271.png">
<img width="701" alt="screen shot 2018-11-13 at 4 36 23 pm" src="https://user-images.githubusercontent.com/18401530/48444600-5f828280-e762-11e8-8975-4594c65281ee.png">

**Comment by twostraws** [comment]
You shouldn’t need to touch the pods. Can you clarify what the build problem was when you did a clean check out?

**Comment by mike011** [comment]
So technically it's not possible to build because the scheme file for Unwrap is not in the repo. In `Unwrap.xcodeproj/project.xcworkspace/xcshareddata` there should be a `Unwrap.xcsheme`, but it is missing. Here is the repo location: https://github.com/twostraws/Unwrap/tree/master/Unwrap.xcodeproj/project.xcworkspace/xcshareddata

**Comment by twostraws** [comment]
Nothing is wrong; I have just configured things in a particular way pending some updates for Swift 4.2 in the pods.
