### ISSUE TITLE
The Unwrap scheme is missing.

### ISSUE THREAD

**Issue by mike011** [twostraws/Unwrap#67]
On launch of the workspace after rebasing with the latest master at the top by the play and stop buttons it says "No Scheme"
<img width="308" alt="screen shot 2019-01-07 at 5 54 23 am" src="https://user-images.githubusercontent.com/705433/50764645-60570280-1241-11e9-9d78-dcc26b081b71.png">

Looks like the Unwrap scheme was either removed from 
./Unwrap.xcodeproj/xcsharedatea/xcschemes/Unwrap.xcsheme or deleted, or had share turned off.

**Comment by twostraws** [comment]
I just did a clean check out and it seems to work fine.
