### ISSUE TITLE
Tab Bar icons pixelated, and titles are shrunk.

### ISSUE THREAD

**Issue by HassanElDesouky** [twostraws/Unwrap#74]
When tapping in a cell in a LearnCoordinator view controller and quickly return back. The tab bar pixelate.
**Tested on iPhone 6s.**

**Before** tapping in any cell in the LearnCoordinator view controller.

![img_4776](https://user-images.githubusercontent.com/13359795/50925032-d3d35c80-1459-11e9-9933-4952668a2b7f.jpeg)

**After** returning back.

![img_4777](https://user-images.githubusercontent.com/13359795/50925045-d7ff7a00-1459-11e9-877f-f080ffb3aab3.jpeg)

**Comment by rahulrs0029** [comment]
This is a problem in iOS, I think. I've had this issue on other apps as well (like WhatsApp)
