### ISSUE TITLE
Bug: Current Streak is not updated

### ISSUE THREAD

**Issue by DavidPiper94** [twostraws/Unwrap#82]
**Describe the bug**
Current Streak is not updated.

**To Reproduce**
Open the app daily for multiple days.

**Expected behavior**
Increasing "Current Streak"-count and "Best Streak"-count on "Home"-Screen.

**Actual behavior**
"Current Streak"-count and "Best Streak"-count are not updated and stay at 1.

**Screenshots**
![img_1982](https://user-images.githubusercontent.com/9396861/51384142-b36f6600-1b1b-11e9-87c0-0494a4a3326d.PNG)
![img_1983](https://user-images.githubusercontent.com/9396861/51384143-b407fc80-1b1b-11e9-82e1-53e1fb1d4dd7.PNG)

As shown in the first screenshot, I completed multiple daily challenges in a row and thus opened the app these days. But as shown in the second screenshot, my "Current Streak"-count does not increase and I did not get the badge either. 

**Smartphone (please complete the following information):**
 - Device: iPhone 7
 - OS: iOS 12.1.1
 - Version 1.0 (2)

**Comment by twostraws** [comment]
I believe this is now fixed – thank you!
