### ISSUE TITLE
Predict the output answers are not case sensitive

### ISSUE THREAD

**Issue by mike011** [twostraws/Unwrap#83]
When you enter the answer for a predict the output question you can enter it all in lower case and the answer is accepted as correct.

![simulator screen shot - iphone 8 - 2019-01-28 at 06 28 09](https://user-images.githubusercontent.com/705433/51833646-08526f80-22c6-11e9-99b4-382222d631c7.png)

**Comment by twostraws** [comment]
This is intentional.
