### ISSUE TITLE
Predict the output answers are incorrect.

### ISSUE THREAD

**Issue by mike011** [twostraws/Unwrap#84]
I've done a ton of the Predict the output questions and I'm not sure exactly why, but these fail. 

![simulator screen shot - iphone 8 - 2019-01-28 at 06 40 31](https://user-images.githubusercontent.com/705433/51834278-d2ae8600-22c7-11e9-8aad-74e0b37354ad.png)
![simulator screen shot - iphone 8 - 2019-01-28 at 06 39 19](https://user-images.githubusercontent.com/705433/51834279-d2ae8600-22c7-11e9-8faf-2bd682343998.png)

**Comment by twostraws** [comment]
I believe this was fixed already. If you're using a build from Git please pull my latest changes and try again.

**Comment by mike011** [comment]
Awesome. I rebased and I couldn't reproduce the == or <= cases
