### ISSUE TITLE
Free Coding method parameters have to be input1, input2, etc.

### ISSUE THREAD

**Issue by mike011** [twostraws/Unwrap#85]
The following fails:
![simulator screen shot - iphone 8 - 2019-01-29 at 04 03 44](https://user-images.githubusercontent.com/705433/51896648-dcdd8c80-237a-11e9-8fe7-9df6899940fc.png)

But if I change the parameters names to input1 and input2 it passes. It isn't intuitive from the question that the parameter names have to be input1 and input2
![simulator screen shot - iphone 8 - 2019-01-29 at 04 07 41](https://user-images.githubusercontent.com/705433/51896767-2d54ea00-237b-11e9-9c72-2add12c35238.png)

I don't know if it would be better to say what the parameter names have to be or make the matching work.

This also fails for other questions where you have to pass in parameter names:
![simulator screen shot - iphone 8 - 2019-01-29 at 04 10 18](https://user-images.githubusercontent.com/705433/51897039-c7b52d80-237b-11e9-985f-f007f6258036.png)

**Comment by twostraws** [comment]
This ought to work now. The problem was that my parameter matching code didn't account for one-letter or one-letter-plus-one-number names, but this has been fixed now and I've added tests to catch this in the future.
